# Generated by Django 2.2.1 on 2019-05-20 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spendingtracker', '0003_auto_20190520_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='records',
            new_name='record',
        ),
    ]
